### ISSUE TITLE
error with link in dce extension

### ISSUE THREAD

**Issue by martin-git-kristensen** [sourcebroker/t3apinews#2]
My setup is typo3 9.5.21 and t3/dce 2.6.0 - and sourcebroker/t3apinews 0.3.3
My problem is when I have a dce record with a link browser button - it fails with the following error:

(1/1) #1381960494 UnexpectedValueException
Your dependencies have cycles. That will not work out. Cycles found: page->tx_news, page->tx_news_tnum, tx_news->page

and then a whole crap of error-codes.

If I have ex a news record with a link browser button there i no problem to get the link browser, så I guess it it the combination of dce and t3apinews. 

Any surgessions ?

Martin

**Comment by kszymukowicz** [comment]
I never saw such error.
t3apinews include automatically this file. 
Try to remove content of this file and see if that helps.

https://github.com/sourcebroker/t3apinews/blob/master/Configuration/TsConfig/Page/mod.tsconfig

**Comment by martin-git-kristensen** [comment]
Hej - you led us in the right way
We have another extension where the same code was:
TCEMAIN.linkHandler.tx_news {
    handler = TYPO3\CMS\Recordlist\LinkHandler\RecordLinkHandler
    label = News
    configuration {
        table = tx_news_domain_model_news
        hidePageTree = 0
    }
    scanBefore = page
}

When I write "scanAfter = page" in our code the problem disappeared :-)

**Comment by kszymukowicz** [comment]
Ok. 
So this issue can be closed. Its not a bug.
